---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: argocd
  labels:
    layer: 'base'
spec:
  destination:
    name: in-cluster
    namespace: default
  sources:
    - path: charts/hello-world
      targetRevision: main
      repoURL: https://github.com/helm/examples.git
      helm:
        values: |
          replicaCount: 1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
